#ifndef COLOR_HEADER
#define COLOR_HEADER

#define FOREGROUND_BLACK	0x0
#define FOREGROUND_BLUE		0x1
#define FOREGROUND_GREEN	0x2
#define FOREGROUND_CYAN		0x3
#define FOREGROUND_RED		0x4
#define FOREGROUND_MAGENTA	0x5
#define FOREGROUND_BROWN	0x6
#define FOREGROUND_WHITE	0x7
#define FOREGROUND_GRAY		0x8
#define FOREGROUND_BR_BLUE	0x9
#define FOREGROUND_BR_GREEN	0xA
#define FOREGROUND_BR_CYAN	0xB
#define FOREGROUND_BR_RED	0xC
#define FOREGROUND_BR_MAGENTA	0xD
#define FOREGROUND_YELLOW	0xE
#define FOREGROUND_BR_WHITE	0xF

#define BACKGROUND_BLACK	0x00
#define BACKGROUND_BLUE		0x10
#define BACKGROUND_GREEN	0x20
#define BACKGROUND_CYAN		0x30
#define BACKGROUND_RED		0x40
#define BACKGROUND_MAGENTA	0x50
#define BACKGROUND_BROWN	0x60
#define BACKGROUND_WHITE	0x70
#define BACKGROUND_GRAY		0x80
#define BACKGROUND_BR_BLUE	0x90
#define BACKGROUND_BR_GREEN	0xA0
#define BACKGROUND_BR_CYAN	0xB0
#define BACKGROUND_BR_RED	0xC0
#define BACKGROUND_BR_MAGENTA	0xD0
#define BACKGROUND_YELLOW	0xE0
#define BACKGROUND_BR_WHITE	0xF0

#endif
